import { z } from "zod";

const themeSchema = z.object({
  accent: z.string().regex(/^#[0-9a-f]{6}$/i),
  glow: z.string().regex(/^#[0-9a-f]{6}$/i),
  signature: z.enum(["rules", "neural", "streams", "trajectory", "pulse", "migration", "modules", "adaptive", "shield", "store"])
});

export const projectSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/),
  displayName: z.string().min(2),
  shortDescription: z.string().min(20),
  problem: z.string().min(30),
  targetUser: z.string().min(10),
  solution: z.string().min(30),
  contribution: z.string().min(30),
  status: z.string().min(3),
  technologies: z.array(z.string()).min(2),
  categories: z.array(z.string()).min(1),
  repositoryUrl: z.string().url(),
  secondaryRepositoryUrl: z.string().url().optional(),
  liveDemoUrl: z.string().url().optional(),
  videoUrl: z.string().url().optional(),
  videoPoster: z.string().startsWith("/"),
  architecture: z.array(z.string()).min(2),
  workflow: z.array(z.string()).min(3),
  technicalDecisions: z.array(z.string()).min(2),
  challenge: z.string().min(30),
  testEvidence: z.array(z.string()).min(1),
  securityNotes: z.array(z.string()).min(1),
  limitations: z.array(z.string()).min(1),
  roadmap: z.array(z.string()).min(1),
  featured: z.boolean(),
  displayOrder: z.number().int().positive(),
  theme: themeSchema,
  relatedProjects: z.array(z.string())
});

export type Project = z.infer<typeof projectSchema>;

const owner = "https://github.com/badugujashwanth-create";
const raw = "https://raw.githubusercontent.com/badugujashwanth-create";

const source: Project[] = [
  {
    slug: "niyamguard",
    displayName: "NiyamGuard",
    shortDescription: "An explainable policy-drift and citizen-service sandbox with auditable rule pathways.",
    problem: "Policy changes can leave citizen portals, forms, eligibility guidance, and operational rules out of sync.",
    targetUser: "Policy operators and citizens exploring synthetic public-service workflows.",
    solution: "A review-first sandbox that extracts synthetic policy changes, models rules, identifies drift, and explains verified decisions without performing real government transactions.",
    contribution: "Designed and implemented the rule/evidence workflow, citizen and operator surfaces, safe simulation boundaries, automated regression suite, and portfolio case study.",
    status: "v1.1.0 released synthetic pilot prototype",
    technologies: ["React", "FastAPI", "SQLAlchemy", "Python", "scikit-learn"],
    categories: ["AI", "Automation", "Full Stack"],
    repositoryUrl: `${owner}/NiyamGuard`,
    videoUrl: `${raw}/NiyamGuard/main/docs/demo/demo.webm`,
    videoPoster: "/assets/projects/niyamguard.png",
    architecture: ["FastAPI policy and service APIs", "SQLAlchemy persistence and synthetic fixtures", "React citizen/operator workflows", "Hybrid rule and assistant boundary"],
    workflow: ["Ingest a synthetic circular", "Extract and review proposed rules", "Compare versions and detect drift", "Publish a verified sandbox rule", "Explain eligibility with evidence"],
    technicalDecisions: ["Deterministic rule evaluation remains authoritative", "Assistant output is bounded by verified policy evidence", "External identity/payment/government actions stay simulated"],
    challenge: "Keeping citizen guidance helpful while preventing generative output from becoming an unreviewed policy authority required a clear rule/evidence boundary.",
    testEvidence: ["243 backend tests", "60 frontend tests", "Vite production build"],
    securityNotes: ["No real government identity, payment, messaging, or submission is claimed", "Optional geolocation requires user action"],
    limitations: ["Synthetic policies and service data", "No verified production government integration"],
    roadmap: ["Broaden reviewed fixtures and accessibility/browser evidence"],
    featured: true,
    displayOrder: 1,
    theme: { accent: "#7c5cff", glow: "#b6a6ff", signature: "rules" },
    relatedProjects: ["nira", "social-media-control-center"]
  },
  {
    slug: "nira",
    displayName: "NIRA",
    shortDescription: "A local-first assistant runtime with permissioned tools, planning, memory controls, and fallbacks.",
    problem: "General assistants often hide tool permissions, external dependencies, and the boundary between suggestions and actions.",
    targetUser: "Developers and operators exploring local, permissioned assistant workflows.",
    solution: "A modular Python runtime that plans work, routes to specialists, confirms sensitive actions, manages memory, and can use local llama.cpp inference when configured.",
    contribution: "Built the orchestration and permission model, tool and fallback boundaries, local-model integration path, test suite, documentation, and case study.",
    status: "v0.5.0 released local-first prototype",
    technologies: ["Python", "pytest", "llama.cpp", "Local tools"],
    categories: ["AI", "Automation", "Security"],
    repositoryUrl: `${owner}/NIRA`,
    videoUrl: `${raw}/NIRA/main/docs/demo/demo.webm`,
    videoPoster: "/assets/projects/nira.png",
    architecture: ["Planner and specialist agents", "Permissioned tool adapters", "Memory and configuration boundary", "Optional local inference server"],
    workflow: ["Parse an operator goal", "Plan bounded steps", "Request permission for sensitive tools", "Execute or recover", "Store only allowed context"],
    technicalDecisions: ["Local-first paths remain optional and explicit", "Tools fail clearly when their runtime is unavailable", "No unrestricted autonomous action"],
    challenge: "The central challenge was making tool use useful without hiding permission decisions or treating an unavailable local model as success.",
    testEvidence: ["51 pytest tests", "Isolated wheel install and CLI verification"],
    securityNotes: ["Explicit permission checks", "Provider and OS tools are environment-dependent"],
    limitations: ["No verified real local-model profile for v0.5.0", "Windows is the only visually audited desktop platform"],
    roadmap: ["Add repeatable local-model resource measurements"],
    featured: true,
    displayOrder: 2,
    theme: { accent: "#00c2a8", glow: "#8bf5e5", signature: "neural" },
    relatedProjects: ["niyamguard", "cricket-intelligence"]
  },
  {
    slug: "social-media-control-center",
    displayName: "Social Media Control Center",
    shortDescription: "A full-stack content workflow joining planning, scheduling, connectors, jobs, and operational state.",
    problem: "Content, schedules, provider connections, approvals, and status become fragmented across channel-specific tools.",
    targetUser: "Small teams coordinating multi-channel content operations.",
    solution: "A Next.js and FastAPI control surface with connector boundaries, scheduling and worker state, explicit configuration, and safe demo behavior.",
    contribution: "Implemented the full-stack workflow, connector contract, job state and errors, web experience, API tests, documentation, and case study.",
    status: "v1.0.0 released simulated-provider prototype",
    technologies: ["Next.js", "FastAPI", "PostgreSQL", "Redis/RQ", "TypeScript", "Python"],
    categories: ["Full Stack", "Automation", "Data"],
    repositoryUrl: `${owner}/social-media-control-center`,
    videoUrl: `${raw}/social-media-control-center/main/docs/demo/demo.webm`,
    videoPoster: "/assets/projects/social-media-control-center.png",
    architecture: ["Next.js static-capable operator UI", "FastAPI service and validation", "Connector abstraction", "Redis/RQ background state"],
    workflow: ["Compose channel-aware content", "Validate connection and schedule", "Queue background work", "Track result or failure", "Review operational state"],
    technicalDecisions: ["Provider-specific logic stays behind connectors", "Absent credentials fail clearly", "Synthetic actions never imply real publishing"],
    challenge: "Representing different provider capabilities without leaking provider-specific behavior through every UI and API path required a stable connector contract.",
    testEvidence: ["19 API tests", "ESLint clean", "Next.js production export"],
    securityNotes: ["Real OAuth/token handling requires provider-specific review", "No portfolio CI publishes to live accounts"],
    limitations: ["Live publishing is not universally verified", "End-to-end browser automation remains limited in the source project"],
    roadmap: ["Add browser coverage for approval, schedule, and recovery"],
    featured: true,
    displayOrder: 3,
    theme: { accent: "#ff6b6b", glow: "#ffc0b8", signature: "streams" },
    relatedProjects: ["workhub-os", "niyamguard"]
  },
  {
    slug: "cricket-intelligence",
    displayName: "Cricket Intelligence System",
    shortDescription: "A dataset-grounded cricket question system with deterministic routing and honest degraded behavior.",
    problem: "Generative sports assistants can return plausible but unsupported statistics, especially when retrieval data is missing.",
    targetUser: "Cricket viewers exploring player, team, match, comparison, and leaderboard questions.",
    solution: "A React client and Express API classify questions, normalize entities, compute typed dataset responses, and preserve an explicit unsupported/degraded path.",
    contribution: "Built the routing and response contracts, dataset paths, web integration, regression cases, startup/status checks, and degraded-retrieval fix.",
    status: "API v1.0.2 and web v1.0.0 released prototypes",
    technologies: ["React", "Express", "Node.js", "Local datasets", "Optional Chroma"],
    categories: ["AI", "Data", "Full Stack"],
    repositoryUrl: `${owner}/cricket-chatbot-api`,
    secondaryRepositoryUrl: `${owner}/cricket-chatbot-web`,
    videoUrl: `${raw}/cricket-chatbot-web/main/docs/demo/demo.webm`,
    videoPoster: "/assets/projects/cricket-intelligence.png",
    architecture: ["React query client", "Express routing and typed responses", "Deterministic dataset services", "Optional local Chroma helper"],
    workflow: ["Normalize the question and entities", "Select a deterministic action", "Compute from available data", "Attach typed evidence", "Return unsupported/degraded guidance when necessary"],
    technicalDecisions: ["Statistics come from deterministic data paths", "Optional retrieval cannot silently downgrade typed team responses", "Unsupported questions remain explicit"],
    challenge: "The regression-prone edge was preserving a frontend-compatible typed response when the optional vector archive was empty or locally broken.",
    testEvidence: ["19 API routing cases", "5 API HTTP integration tests", "3 web Playwright workflows", "API and web production checks"],
    securityNotes: ["No language-model-generated statistic is treated as evidence", "Public deployment would require request abuse limits"],
    limitations: ["Optional Chroma archive is empty in the verified environment", "Dataset scope bounds available answers"],
    roadmap: ["Add provenance and golden statistical calculations for common queries"],
    featured: true,
    displayOrder: 4,
    theme: { accent: "#f6c945", glow: "#ffe79a", signature: "trajectory" },
    relatedProjects: ["nira", "heart-analysis"]
  },
  {
    slug: "heart-analysis",
    displayName: "Heart Analysis",
    shortDescription: "An educational health-risk exploration workflow with explanations and explicit non-diagnostic limits.",
    problem: "Health-risk model output can be opaque, easy to overstate, and difficult for users to interpret safely.",
    targetUser: "Learners exploring how inputs affect an educational risk model—not patients seeking diagnosis.",
    solution: "A Flutter and Flask application presents validated inputs, risk exploration, explanations, history, and reports with visible safety language.",
    contribution: "Implemented and verified backend analysis paths, Flutter interfaces, explanation/report workflows, tests, build guidance, and portfolio evidence.",
    status: "v1.0.0 released educational prototype",
    technologies: ["Flutter", "Dart", "Flask", "SQLAlchemy", "Python"],
    categories: ["Data", "Full Stack"],
    repositoryUrl: `${owner}/heart-analysis`,
    videoUrl: `${raw}/heart-analysis/main/docs/demo/demo.webm`,
    videoPoster: "/assets/projects/heart-analysis.png",
    architecture: ["Flutter web/mobile client", "Flask analysis API", "SQLAlchemy history boundary", "Explanation and report layer"],
    workflow: ["Enter validated educational inputs", "Run the bounded analysis", "Review explanation and limitations", "Inspect history or report"],
    technicalDecisions: ["Non-diagnostic language is part of the product boundary", "Checks run per package because nested Flutter roots conflict", "Sensitive deployment requires a separate threat model"],
    challenge: "The product had to make model output understandable without turning an educational risk estimate into medical advice.",
    testEvidence: ["19 backend tests", "2 Flutter widget tests", "2 Chromium workflows", "Ruff clean and Flutter web release build"],
    securityNotes: ["Educational, non-diagnostic use only", "No real patient deployment is claimed"],
    limitations: ["No clinical validation", "Overlapping Flutter package structure remains technical debt"],
    roadmap: ["Designate one canonical mobile package and add browser accessibility coverage"],
    featured: true,
    displayOrder: 5,
    theme: { accent: "#ff4d8d", glow: "#ffb3cf", signature: "pulse" },
    relatedProjects: ["cricket-intelligence", "niyamguard"]
  },
  {
    slug: "zettalogix-migration-suite",
    displayName: "Zettalogix Migration Suite",
    shortDescription: "A migration-control frontend with a deterministic, network-free workflow for public evaluation.",
    problem: "Migration operators need a clear way to configure sources and targets, track jobs, inspect risk, and recover from state changes.",
    targetUser: "Content-migration operators evaluating a control-plane interface.",
    solution: "React and Electron clients model connections, jobs, progress, history, settings, and reporting; a synthetic session exercises real local state transitions without credentials.",
    contribution: "Built and strengthened the frontend, explicit frontend/backend boundary, synthetic state machine, no-network tests, documentation, deployment evidence, and recruiter path.",
    status: "v0.3.0 released frontend prototype; external backend/workers",
    technologies: ["React", "TypeScript", "Vite", "Electron", "Supabase client"],
    categories: ["Migration", "Full Stack", "Automation"],
    repositoryUrl: `${owner}/zettalogix-migration-suite`,
    liveDemoUrl: "https://sharepoint-one.vercel.app/login?demo=1",
    videoUrl: `${raw}/zettalogix-migration-suite/main/docs/demo/demo.webm`,
    videoPoster: "/assets/projects/zettalogix-migration-suite.png",
    architecture: ["React/Vite operator UI", "Electron wrapper", "Live API adapter", "In-memory synthetic adapter with session-scoped mode"],
    workflow: ["Enter the clearly labeled synthetic mode", "Inspect connections and migration jobs", "Create and start a job", "Pause and inspect history", "Export a synthetic CSV report"],
    technicalDecisions: ["Demo mode branches before authentication/network work", "Synthetic data is fictional and deterministic", "External backend ownership stays explicit"],
    challenge: "The baseline frontend depended on external auth and workers; the solution had to demonstrate meaningful migration state without faking production migrations.",
    testEvidence: ["7 web tests", "2 desktop boundary tests", "TypeScript/Vite production builds", "Live Vercel route verified"],
    securityNotes: ["Synthetic mode makes no Supabase, provider, or migration API requests", "Browser env example contains placeholders only"],
    limitations: ["Migration backend and worker are external", "No successful production migration is claimed"],
    roadmap: ["Add browser smoke and checkpoint/retry views after an owned worker contract exists"],
    featured: true,
    displayOrder: 6,
    theme: { accent: "#4e7cff", glow: "#abc0ff", signature: "migration" },
    relatedProjects: ["social-media-control-center", "workhub-os"]
  },
  {
    slug: "workhub-os",
    displayName: "WorkHub OS",
    shortDescription: "A broad role-based work operations prototype with tasks, attendance, collaboration, and reporting.",
    problem: "Small teams often split operational workflows across disconnected tools.",
    targetUser: "Teams exploring a unified operational workspace.",
    solution: "A Next.js client and Express/MongoDB service surface role, work, task, chat, attendance, and reporting modules.",
    contribution: "Built the prototype and added tested CORS security boundaries and honest deployment documentation.",
    status: "v1.1.0 released secondary prototype",
    technologies: ["Next.js", "Express", "MongoDB", "Socket.IO"],
    categories: ["Full Stack", "Automation"],
    repositoryUrl: `${owner}/workhub-os`,
    videoUrl: `${raw}/workhub-os/main/docs/demo/demo.webm`,
    videoPoster: "/assets/projects/workhub-os.png",
    architecture: ["Next.js frontend", "Express API", "MongoDB models", "Socket.IO services"],
    workflow: ["Authenticate", "Enter a workspace", "Manage work and tasks"],
    technicalDecisions: ["Explicit CORS allowlist", "Frontend and backend verified separately"],
    challenge: "Breadth exceeded the depth of verified database-backed workflows.",
    testEvidence: ["5 CORS tests", "2 authenticated MongoDB workflow tests", "Frontend lint and 37-route build"],
    securityNotes: ["Historical credential requires provider-side rotation", "Full authorization testing remains pending"],
    limitations: ["Backend startup and authenticated integration path not verified"],
    roadmap: ["Add ephemeral-database authorization integration tests"],
    featured: false,
    displayOrder: 7,
    theme: { accent: "#43d17d", glow: "#a7f5c2", signature: "modules" },
    relatedProjects: ["social-media-control-center", "zettalogix-migration-suite"]
  },
  {
    slug: "neutro",
    displayName: "Neutro",
    shortDescription: "An experimental accessibility-adaptation interface focused on explainable preference changes.",
    problem: "Interfaces often ignore individual sensory and interaction preferences.",
    targetUser: "People exploring configurable interface adaptation.",
    solution: "A preference-oriented interface concept for typography, motion, contrast, and state adaptation.",
    contribution: "Implemented the interface and repaired lint/build issues while documenting ethical and evidence limits.",
    status: "Experimental",
    technologies: ["React", "TypeScript", "Vite"],
    categories: ["Accessibility", "Experimental"],
    repositoryUrl: `${owner}/Neutro`,
    videoUrl: `${raw}/Neutro/main/docs/demo/demo.webm`,
    videoPoster: "/assets/projects/neutro.png",
    architecture: ["React interface", "Preference state"],
    workflow: ["Choose preferences", "Apply adaptation", "Reset state"],
    technicalDecisions: ["No medical claims", "Optional device integrations stay separate"],
    challenge: "Measurable accessibility outcomes still require behavioral tests.",
    testEvidence: ["ESLint clean", "Two production builds"],
    securityNotes: ["Camera/privacy boundaries remain optional and explicit"],
    limitations: ["No meaningful automated adaptation tests"],
    roadmap: ["Add deterministic transformation and accessibility tests"],
    featured: false,
    displayOrder: 8,
    theme: { accent: "#45a3ff", glow: "#b2dcff", signature: "adaptive" },
    relatedProjects: ["nira"]
  },
  {
    slug: "shadowops",
    displayName: "ShadowOps",
    shortDescription: "A collaborative hackathon fork retained with explicit upstream and individual attribution.",
    problem: "Security/ML experiments require reproducible evidence and precise ownership boundaries.",
    targetUser: "Reviewers of the attributed hackathon collaboration.",
    solution: "A fork containing shared artifacts plus portfolio-branch lite runtime, CI, tests, docs, and demo work.",
    contribution: "Portfolio work is limited to documented lite-runtime test dependency, CI, documentation, demo, and an earlier upstream PR.",
    status: "Collaborative experiment / fork",
    technologies: ["Python", "Machine learning", "React"],
    categories: ["Security", "Experimental"],
    repositoryUrl: `${owner}/shadowops-hackathon`,
    videoUrl: `${raw}/shadowops-hackathon/main/docs/demo/demo.webm`,
    videoPoster: "/assets/projects/shadowops.png",
    architecture: ["Shared ML artifacts", "Lite runtime and frontend"],
    workflow: ["Review attribution", "Run lite checks", "Inspect shared artifacts"],
    technicalDecisions: ["Fork status is prominent", "No sole model-training claim"],
    challenge: "Upstream/team history makes individual ownership difficult to isolate.",
    testEvidence: ["Lite runtime and frontend CI"],
    securityNotes: ["Model/security effectiveness requires upstream evidence"],
    limitations: ["Individual contribution is not strong enough for flagship use"],
    roadmap: ["Prefer upstream contributions over portfolio-only expansion"],
    featured: false,
    displayOrder: 9,
    theme: { accent: "#9d7bff", glow: "#d1c2ff", signature: "shield" },
    relatedProjects: ["nira"]
  },
  {
    slug: "hyd-vntg-storefront",
    displayName: "HYD VNTG Storefront",
    shortDescription: "A responsive vintage storefront prototype with fail-closed local demo administration.",
    problem: "Small catalog concepts need a coherent browsing and cart experience without fake payment claims.",
    targetUser: "Shoppers evaluating a frontend catalog prototype.",
    solution: "A responsive React storefront with catalog, cart, and explicitly local/demo admin configuration.",
    contribution: "Built the storefront and removed default credentials, fixed dependencies, verified the build, and packaged real video evidence.",
    status: "Supporting prototype",
    technologies: ["React", "Vite", "JavaScript"],
    categories: ["Full Stack"],
    repositoryUrl: `${owner}/hyd-vntg-storefront`,
    videoUrl: `${raw}/hyd-vntg-storefront/main/docs/demo/demo.webm`,
    videoPoster: "/assets/projects/hyd-vntg-storefront.png",
    architecture: ["React client", "Local demo store"],
    workflow: ["Browse catalog", "Manage cart", "Use configured local demo admin"],
    technicalDecisions: ["No fallback credentials", "No fake payment flow"],
    challenge: "Client-side admin behavior had to be described honestly and fail closed.",
    testEvidence: ["Vite build", "0 production dependency vulnerabilities"],
    securityNotes: ["Client-side admin is not a production authorization boundary"],
    limitations: ["No production commerce backend"],
    roadmap: ["Add browser workflow tests before deeper expansion"],
    featured: false,
    displayOrder: 10,
    theme: { accent: "#db9464", glow: "#ffd0ae", signature: "store" },
    relatedProjects: ["social-media-control-center"]
  },
  {
    slug: "parking-alert",
    displayName: "Parking Alert",
    shortDescription: "An experimental mobile parking-notification workflow held behind a Firebase security gate.",
    problem: "Parking and vehicle-contact situations need a clear notification workflow without exposing unsafe cloud access.",
    targetUser: "Mobile users evaluating the experimental alert workflow.",
    solution: "A Flutter/Firebase application prototype for registering and receiving parking-related alerts.",
    contribution: "Built the mobile workflow and documented the repository security gate, current-tree scan, and external Firebase verification requirements.",
    status: "Experimental / Firebase security hold",
    technologies: ["Flutter", "Dart", "Firebase"],
    categories: ["Full Stack", "Security", "Experimental"],
    repositoryUrl: `${owner}/parkalert-india`,
    videoUrl: `${raw}/parkalert-india/main/docs/demo/demo.webm`,
    videoPoster: "/assets/projects/parking-alert.png",
    architecture: ["Flutter mobile client", "Externally configured Firebase services"],
    workflow: ["Configure a device", "Create an alert", "Observe notification state"],
    technicalDecisions: ["Repository evidence cannot substitute for Firebase console review", "Release remains held until rules and restrictions are verified"],
    challenge: "A client API key is not a server secret, but its safety depends on cloud restrictions and rules that cannot be proven from source alone.",
    testEvidence: ["One smoke test", "Current tracked-tree Gitleaks scan clean"],
    securityNotes: ["Ignored local client key and history require console restriction evidence", "No complete Firebase security claim"],
    limitations: ["Deployed rules, App Check, authorized domains, and key restrictions are unverified"],
    roadmap: ["Verify cloud console state and add emulator-based unauthorized-access tests"],
    featured: false,
    displayOrder: 11,
    theme: { accent: "#ff9f43", glow: "#ffd39b", signature: "shield" },
    relatedProjects: ["neutro"]
  }
];

export const projects = z.array(projectSchema).parse(source).sort((a, b) => a.displayOrder - b.displayOrder);
export const featuredProjects = projects.filter((project) => project.featured);
export const projectBySlug = new Map(projects.map((project) => [project.slug, project]));

export const categories = Array.from(new Set(projects.flatMap((project) => project.categories))).sort();
